// app/layout.jsx
import 'bootstrap/dist/css/bootstrap.min.css';
import Script from 'next/script';
import './globals.css'; // Importando o arquivo globals.css
import Header from './components/Header';

export const metadata = {
  title: 'Blasco Advogados',
  description: 'Generated by Otávio & Giovana',
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <head>
        <title>Blasco Advogados</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" /> {/* Meta viewport para responsividade */}
      </head>
      <body>
        <Header />
        {children}
        <Script
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
          integrity="sha384-IQsoLXlF0CQqdL0S1fAXSYug56LJ2lIS7z4ql8f3g7Pjt5H1mI4FJ9DOfd83Xb0y"
          crossOrigin="anonymous"
        />
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
          integrity="sha384-cV4irWB5y8q7/9+S8mxHj3atL8QLZXP7Bq5P34PstSH/oBlB6yEGOtq0Mcsw9fwi"
          crossOrigin="anonymous"
        />
      </body>
    </html>
  );
}
